### ISSUE TITLE
Bugs in file name editing in Page 3 (Keypresses Decoder)

### ISSUE THREAD

**Issue by judmn** [INVOKE-Solutions/streamlit_ivr_survey_automation#10]
In 'Keypresses Decoder' page, when I edit the file name before download, the bottom part refreshes and it goes back to before we hit 'Decode Keypresses' button.

I figured out that when I edited the file name (again) and proceed with download anyway, the edited name actually reflected on the worksheet (tab) name, not the file name.

**Comment by fahmizainal17** [comment]
Done.
