### ISSUE TITLE
Change 'Used Phone Numbers'  into 'Dialed Phone Numbers' on Page 1

### ISSUE THREAD

**Issue by judmn** [INVOKE-Solutions/streamlit_ivr_survey_automation#6]
![image](https://github.com/INVOKE-Solutions/streamlit_ivr_survey_automation/assets/62960813/ee5a9df5-3e37-4ed0-9467-cfe2b5655913)

**Comment by fahmizainal17** [comment]
done 

# Convert the unique phone numbers dataframe to CSV for download
                phonenum_data_as_csv = phonenum_combined.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="Download Dialed Phone Numbers as CSV",
                    data=phonenum_data_as_csv,
                    file_name=output_filename_phonenum,
                    mime='text/csv'
                )
