### ISSUE TITLE
Change default file name into something more general

### ISSUE THREAD

**Issue by judmn** [INVOKE-Solutions/streamlit_ivr_survey_automation#7]
Page 1:
![image](https://github.com/INVOKE-Solutions/streamlit_ivr_survey_automation/assets/62960813/daf3412f-083b-401c-9f51-3f5d53e32884)

Page 3:
![image](https://github.com/INVOKE-Solutions/streamlit_ivr_survey_automation/assets/62960813/f11bf99f-922f-4794-a377-4263acbd8860)

**Comment by fahmizainal17** [comment]
done 

page 1 

# Format the default filename
            default_filename = f'IVR_Cleaned_Data_v{formatted_date}.csv'

            # Use the default filename in the text input, allowing the user to edit it
            output_filename = st.text_input("Edit the filename for download", value=default_filename)

            # Check if the output filename ends with '.csv', if not append '.csv'
            if not output_filename.lower().endswith('.csv'):
                output_filename += '.csv'
            
            # After data processing
            st.session_state['cleaned_data'] = combined_data

            # Download button
            data_as_csv = combined_data.to_csv(index=False).encode('utf-8')
            st.download_button(
                label="Download Cleaned Data as CSV",
                data=data_as_csv,
                file_name=output_filename,
                mime='text/csv'
            )




 # Current date for the filename specific to unique phone numbers
                formatted_date = datetime.now().strftime("%Y%m%d")
                default_filename_phonenum = f'IVR_Dialed_Phonenum_v{formatted_date}.csv'
                output_filename_phonenum = st.text_input("Edit the filename for download", value=default_filename_phonenum)

                # Ensure the filename ends with '.csv'
                if not output_filename_phonenum.lower().endswith('.csv'):
                    output_filename_phonenum += '.csv'

                # Convert the unique phone numbers dataframe to CSV for download
                phonenum_data_as_csv = phonenum_combined.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="Download Dialed Phone Numbers as CSV",
                    data=phonenum_data_as_csv,
                    file_name=output_filename_phonenum,
                    mime='text/csv'
                )
                
                
                
  Page 3
  
  
            # Initialize session state for output_filename if it doesn't already exist
            if 'output_filename' not in st.session_state:
                formatted_date = datetime.now().strftime("%Y%m%d")
                st.session_state['output_filename'] = f'IVR_Decoded_Data_v{formatted_date}.csv'
