### ISSUE TITLE
Amend the 'Sanity check' part on Page 3

### ISSUE THREAD

**Issue by judmn** [INVOKE-Solutions/streamlit_ivr_survey_automation#8]
![image](https://github.com/INVOKE-Solutions/streamlit_ivr_survey_automation/assets/62960813/e0007a91-75b6-4e95-b7b5-404ec2cb12e7)

1. Just make a single print "Sanity check for values in each column" on top, no need to repeat for every column.
2. Exclude `phonenum` column. Can add `if col != 'phonenum':`

**Comment by fahmizainal17** [comment]
done 

st.markdown("### Sanity check for values in each column")
            for col in renamed_data.columns:
                if col != 'phonenum':
                    st.write(renamed_data[col].value_counts(normalize=True))
                    st.write("\n")
