### ISSUE TITLE
Amend NULL values inspection

### ISSUE THREAD

**Issue by judmn** [INVOKE-Solutions/streamlit_ivr_survey_automation#9]
![image](https://github.com/INVOKE-Solutions/streamlit_ivr_survey_automation/assets/62960813/fdc20b09-e531-4e75-ada2-c96f0a822f34)

1. Print 'Null Values Inspection' at the top
2. Remove `Before dropping:` as original no. of rows already shown as `IVR Length`
3. Change `After dropping` into `No. of rows after dropping nulls`

**Comment by fahmizainal17** [comment]
done change
